---

- name: Ensure user system groups exists
  group:
    name: '{{ item.name }}'
    system: "{{ item.system | default('false') }}"
    state: "{{ item.state | default('present') }}"
  loop: '{{ ssh_groups }}'
