---

- name: Be sure ssh is installed
  apt:
    name: '{{ ssh_server_packages }}'
    state: present

- name: Start ssh service
  service:
    name: ssh
    state: started
    enabled: true

- name: Update ssh server configuration
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600
    validate: 'sshd -T -f %s'
  notify: restart ssh

- name: Remove sshd_config.ucf-dist, if available
  file:
    path: /etc/ssh/sshd_config.ucf-dist
    state: absent

- name: Update ssh client configuration
  template:
    src: ssh_config.j2
    dest: /etc/ssh/ssh_config
    owner: root
    group: root
    mode: 0644
